### ISSUE TITLE
Documentation for Bevy versioning support

### ISSUE THREAD

**Issue by ActuallyHappening** [FrankenApps/meshtext#1]
Hello, would you mind adding a table with bevy versions -> mesh text versions?
This will help people evaluating the usability of your crate, especially if they want to try use it with `bevy`s main branch

**Comment by FrankenApps** [comment]
This crate is not tied to any special version, because all it does is creating a mesh from a font and a string (in fact it does not even use bevy).
However I will make it more transparent in the sample application for bevy over [here](https://github.com/FrankenApps/bevy_meshtext_sample).
